<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>AlphaPascal.Math.Regression</Title>
    <Company>AlphaPascal</Company>
    <Description>The library for working with regression analysis from Alfapascal</Description>
    <PackageIcon>icon-ap.png</PackageIcon>
    <PackageTags>Regression, Linear, Spline, AlphaPascal </PackageTags>
    <PackageReadmeFile>Descriptions.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Packaging\Descriptions.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="Packaging\icon-ap.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MathNet.Symbolics" Version="0.25.0" />
  </ItemGroup>
	
	<PropertyGroup>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Version>1.1.0</Version>
	</PropertyGroup>

</Project>
